spring:
  datasource:
    driver: org.h2.Driver
    url: jdbc:h2:mem:bootapp;DB_CLOSE_DELAY=-1
    username: sa
    password:


  data:
    rest:
      basePath: /api

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org: DEBUG
